name: flatbuffers_dart_benchmark
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  benchmark_harness: any
  # latest flatbuffers from git has performance-improving patches
  flat_buffers:
    git:
      url: https://github.com/google/flatbuffers
      ref: c0ba2870c909fb57f97efd7083b5d33d2311d7f9
      path: dart
  objectbox: 1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

